.TH "repoview" "8" "0.1" "Konstantin Ryabitsev" "Applications/Utilities"

.SH NAME
\fBrepoview\fR \- Make YUM repositories browseable

.SH SYNOPSIS
\fBrepoview\fR [\-i name] [\-x arch] [\-k dir] [\-l title] [\-t] [\-f] [\-q] repodir

.SH DESCRIPTION
RepoView allows one to easily create a set of static HTML pages in a 
YUM repository, allowing simple browsing of available packages. It uses 
kid templating engine to create the pages and is therefore easily 
customizeable.

.SH OPTIONS
.TP
.B \-i name
Optionally ignore this package \-\- can be a shell-style glob.
This is useful for excluding debuginfo packages:
.br
\-i *debuginfo* \-i *doc*
.br
The globbing will be done against name-epoch-version-release, e.g. 
foo-0-1.0-1
.TP
.B \-x arch
Optionally exclude this arch. E.g.:
.br
\-x src \-x ia64
.TP
.B \-k dir
Use an alternative directory with kid templates instead of the 
default: ./templates. The template directory must contain three 
required template files: index.kid, group.kid, package.kid and 
the "layout" dir which will be copied into the repoview directory.
.TP
.B \-l title
Describe the repository in a few words. By default "RepoView" is used. 
E.g.:
.br
-l "Extras for Fedora Core 3 x86"
.TP
.B \-t
Place the index.html into the top level of the repodir, instead of
just in repodata/index.html.
.TP
.B \-f
Regenerate the pages even if the repomd checksum has not changed.
.TP
.B \-q
Do not output anything except fatal erros.
.TP
.B \-V, \-\-version
Print version number and exit.
.TP
.B \-h, \-?, \-\-help
Print usage message and exit.
.TP
.B repodir
Where to look for the "repodata" directory.

.SH "FILES"
.LP 
.I /usr/bin/repoview
.br
.I /usr/share/repoview/templates/*

.SH "EXAMPLES"
.LP
The simplest invocation is:
.LP 
.B repoview /path/to/repository
.br
.B repoview -l "Fedora Extras 3 ix86" /path/to/repository
.LP 
When running from cron, you want to use the \-q switch:
.LP 
.B repoview -q /path/to/repository

.SH "AUTHORS"
.LP 
Konstantin Ryabitsev <icon@linux.duke.edu>

.SH "SEE ALSO"
.LP 
http://linux.duke.edu/metadata
